import { ToastContainer } from "react-toastify";
import "./globals.css";
import { Inter, Jost } from "next/font/google";
import Providers from "../utils/provider";
import Navbar from "../components/navbar/Navbar";
import { ReduxProvider } from "../redux/provider";
import Footer from "../components/footer/Footer";
import NewsLetter from "../components/newsletter/NewsLetter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shein Style",
  description: "Generated by create next app",
};

const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "900"],
  variable: "--font-jost",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jost.variable}>
      {/* <link
        rel="stylesheet"
        type="text/css"
        href="../assets/flaticons/flaticon_farmacy.css"
      /> */}
      <script async src="//www.instagram.com/embed.js"></script>
      <body className="font-jost relative">
        {/* <NavSearch/> */}
        <ReduxProvider>
          <Providers>
            {/* <SearchHeader/> */}
            <Navbar />
            {children}
            <NewsLetter />
            <Footer />
            <ToastContainer />
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
